name: CI

on:
  pull_request:

env:
  NODE_ENV: production

jobs:
  test:
    name: Run frontend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atcoder-problems-frontend

      strategy:
        matrix:
          node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn
    - name: build
      run: yarn build
    - name: test
      run: yarn test
