name: Build and Test Juno Frontend Application

on:
  pull_request:

env:
  NODE_ENV: production

jobs:
  test:
    name: Run frontend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    # repository を checkout
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      # NODE_ENV=production となっていると devDependencies がインストールされないため，
      # --production=false オプションを付与してインストールされるようにしている
      run: yarn install --production=false

    - name: Build
      run: yarn build

    - name: test
      run: yarn test
